version: '3.8'

networks:
  frontend:
    external:
      name: reverse-proxy

services:
  nginx:
    image: nginx:latest
    restart: always
    networks:
      - frontend
    volumes:
      - ./.vuepress/dist:/usr/share/nginx/html:ro
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=reverse-proxy"
      # https
      - "traefik.http.routers.thomasventurini-blog.rule=Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`)"
      - "traefik.http.routers.thomasventurini-blog.entrypoints=${ENTRYPOINT}"
      - "traefik.http.routers.thomasventurini-blog.tls=true"
      - "traefik.http.routers.thomasventurini-blog.tls.certresolver=letsencrypt"
      # middlewares
      - "traefik.http.routers.thomasventurini-blog.middlewares: redirect-to-non-www"
